# Generated by Django 4.1.7 on 2023-03-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Emp_id", models.IntegerField()),
                ("Emp_name", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("check_in", models.TimeField()),
                ("check_out", models.TimeField()),
            ],
        ),
    ]
